INSERT INTO "products" VALUES(1,10,"VIZIO E-Series E43-C2 Full-Array Full HD Smart LED TV",458.23,'file:///android_asset/images/products/television_1.jpg');
INSERT INTO "products" VALUES(2,10,"VIZIO E-Series E40-C2 Full-Array Full HD Smart LED TV",785.12,'file:///android_asset/images/products/television_2.jpg');
INSERT INTO "products" VALUES(3,10,"VIZIO E-Series E32-C2 Full-Array Full HD Smart LED TV",258,'file:///android_asset/images/products/television_3.jpg');
INSERT INTO "products" VALUES(4,10,"Sharp 80 LC-43LE56U AQUOS Full HD Smart LED TV",299.7,'file:///android_asset/images/products/television_4.jpg');
INSERT INTO "products" VALUES(5,10,"LG LF58000 Full HD Smart LED TV",789,'file:///android_asset/images/products/television_5.jpg');
INSERT INTO "products" VALUES(6,10,"Samsung J5765 Full HD Smart LED TV",199.78,'file:///android_asset/images/products/television_6.jpg');
INSERT INTO "products" VALUES(7,10,"Sony W600 Full HD Smart LED TV",422.44,'file:///android_asset/images/products/television_7.jpg');
INSERT INTO "products" VALUES(8,10,"Sharp W7987 Smart 3d TV",456,'file:///android_asset/images/products/television_8.jpg');
INSERT INTO "products" VALUES(9,17,"Samsung HT-j687 5.1 Network Home Theater System",1255.1,'file:///android_asset/images/products/home_theater_1.jpg');
INSERT INTO "products" VALUES(10,17,"Sony BD-7689 Home Theater System with Wi-Fi",8963.45,'file:///android_asset/images/products/home_theater_2.jpg');
INSERT INTO "products" VALUES(11,17,"VIZIO SB6789-C1 Blu-ray Home Theater System",87543.45,'file:///android_asset/images/products/home_theater_3.jpg');
INSERT INTO "products" VALUES(12,17,"Samsung HT-H56 5.1 Home Theater System",987.41,'file:///android_asset/images/products/home_theater_4.jpg');
INSERT INTO "products" VALUES(13,17,"Bose CineMate 520 Home Theater System",8954.23,'file:///android_asset/images/products/home_theater_5.jpg');
INSERT INTO "products" VALUES(14,17,"Onkyo HT-S776 5.1.2 Home Theater System",8520.23,'file:///android_asset/images/products/home_theater_6.jpg');
INSERT INTO "products" VALUES(15,17,"Bose Lifestyle 564 III Home Theater System",656.45,'file:///android_asset/images/products/home_theater_7.jpg');
INSERT INTO "products" VALUES(16,17,"Yamaha YHT-798 5.1 Home Theater System",963.11,'file:///android_asset/images/products/home_theater_8.jpg');
INSERT INTO "products" VALUES(17,18,"Samsung HT-j687 5.1 Network Home Theater System",8963.24,'file:///android_asset/images/products/receiver_1.jpg');
INSERT INTO "products" VALUES(18,18,"Sony BD-7689 Home Theater System with Wi-Fi",8756.44,'file:///android_asset/images/products/receiver_2.jpg');
INSERT INTO "products" VALUES(19,18,"VIZIO SB6789-C1 Blu-ray Home Theater System",9865.78,'file:///android_asset/images/products/receiver_3.jpg');
INSERT INTO "products" VALUES(20,18,"Samsung HT-H56 5.1 Home Theater System",6532.12,'file:///android_asset/images/products/receiver_4.jpg');
INSERT INTO "products" VALUES(21,18,"Bose CineMate 520 Home Theater System",885.52,'file:///android_asset/images/products/receiver_5.jpg');
INSERT INTO "products" VALUES(22,18,"Onkyo HT-S776 5.1.2 Home Theater System",325.14,'file:///android_asset/images/products/receiver_6.jpg');
INSERT INTO "products" VALUES(23,18,"Bose Lifestyle 564 III Home Theater System",456,'file:///android_asset/images/products/receiver_7.jpg');
INSERT INTO "products" VALUES(24,18,"Yamaha YHT-798 5.1 Home Theater System",699.8,'file:///android_asset/images/products/receiver_8.jpg');
INSERT INTO "products" VALUES(25,2,"ASUS ZenFone 2 ZE345 16GB Smartphone",199.99,'file:///android_asset/images/products/mobile_1.jpg');
INSERT INTO "products" VALUES(26,2,"ASUS ZenFone 2 ZE678 32GB Smartphone",374.55,'file:///android_asset/images/products/mobile_2.jpg');
INSERT INTO "products" VALUES(27,2,"LG G2 D801 32GB Black Unlocked Smartphone",229.99,'file:///android_asset/images/products/mobile_3.jpg');
INSERT INTO "products" VALUES(28,2,"Galaxy S6 SM-G9687 32GB Black Sapphire",204.99,'file:///android_asset/images/products/mobile_4.jpg');
INSERT INTO "products" VALUES(29,2,"Samsung Galaxy Note 4 SM-N810C 64GB(Charcoal Black)",125.88,'file:///android_asset/images/products/mobile_5.jpg');
INSERT INTO "products" VALUES(30,2,"LG G3 D855 International 32GB(Metallic Black)",134,'file:///android_asset/images/products/mobile_6.jpg');
INSERT INTO "products" VALUES(31,2,"Samsung Galaxy S5 SM-G900F 16GB Black",139,'file:///android_asset/images/products/mobile_7.jpg');
INSERT INTO "products" VALUES(32,2,"BlackBerry Classic SQC100-4 16 GB Smartphone",289.56,'file:///android_asset/images/products/mobile_8.jpg');
INSERT INTO "products" VALUES(33,2,"BLU Life Pure Mini 16GB(White)",456,'file:///android_asset/images/products/mobile_9.jpg');
INSERT INTO "products" VALUES(34,2,"Microsoft Lumia 640 XL RM-1065 8GB Dual Sim",539.12,'file:///android_asset/images/products/mobile_10.jpg');
INSERT INTO "products" VALUES(35,2,"Sony Xperia Z3 Compact D590 16 GB",426.45,'file:///android_asset/images/products/mobile_11.jpg');
INSERT INTO "products" VALUES(36,2,"BLU Vivo IV D7687 16GB Smartphone",456,'file:///android_asset/images/products/mobile_12.jpg');
INSERT INTO "products" VALUES(37,2,"Samsung Galaxy Note 4 32GB",789.12,'file:///android_asset/images/products/mobile_13.jpg');
INSERT INTO "products" VALUES(38,2,"Galaxy Grand Prime SM-G6876 8GB Smartphone",458.45,'file:///android_asset/images/products/mobile_14.jpg');
INSERT INTO "products" VALUES(39,2,"Huawie Ascend Mate2 MT2_L03 4G 16GB",535.78,'file:///android_asset/images/products/mobile_15.jpg');
